robot_radius: 0.075 # 机器人半径

obstacle_range: 2.5 # 规避障碍的范围
raytrace_range: 3.5 # 探测障碍的范围
#footprint: [[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25]]
footprint_inflation: 0.055 # 机器人膨胀层

inflation_radius: 0.10
cost_scaling_factor: 0.55

max_obstacle_height: 0.5

observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
